name: Deploy static content to GitHub Pages
env:
  PUBLISH_DIR: MyCorner/bin/Release/net8.0/publish/wwwroot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: '8.0'

      - name: Publish
        run: dotnet publish MyCorner -c Release

      - name: List output files
        run: ls -alhR ${{ env.PUBLISH_DIR }}

      - name: Verify index.html exists
        run: |
            if [ ! -f "${{ env.PUBLISH_DIR }}/index.html" ]; then
              echo "index.html not found! Failing."
              exit 1
            fi

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0  
                  
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
          
                
      
